### ISSUE TITLE
Build Java Version Errors

### ISSUE THREAD

**Issue by xzippyzachx** [PBaciu/tabToMXL#23]
**Reproduction:** Following the installation instructions provided by your user manual  [https://github.com/PBaciu/tabToMXL/blob/master/README.md](url) the error seen in screenshot 1 was produced when running the project.

**Expected:** The gradle build should automatically install the required Java JDK version.

**Actual:** For some reason the gradle build was not installing the Java JDK version 15 when building.

**Proposed Solution:** I was able to troubleshoot the issue. I modified the build.gradle file to be the following 
[FixedBuild.Gradle.txt](https://github.com/PBaciu/tabToMXL/files/6191826/FixedBuild.Gradle.txt)
I changed
```
sourceCompatibility = 15.0
targetCompatibility = 15.0
```
to be
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(15)
    }
}
```
This seemed to fix the Java JDK version issue

**Priority:** High

**Severity:** High - Some users could not run your program 3/5 of our group members had this issue

**Screenshots:**
![image](https://user-images.githubusercontent.com/33043402/112193638-782abf00-8bde-11eb-8302-25e7717e7104.png)
_Could not target platform: 'Java SE 15' using tool chain: 'JDK 11 (11)_
![image](https://user-images.githubusercontent.com/33043402/112195192-0c495600-8be0-11eb-9ec9-cef3f914a048.png)
_Modified code added to the build.gradle_

**Comment by PBaciu** [comment]
Thank you for the solution Zachary, this will be tested on a machine not running Java 15, and will be implemented in a future release.

**Comment by PBaciu** [comment]
Resolved
