### ISSUE TITLE
Save Changes Prompt When No Changes Made

### ISSUE THREAD

**Issue by ErikaGrandy** [PBaciu/tabToMXL#26]
**Issue Title:** Save Changes Prompt When No Changes Made

**Version:** TabToXML March 17 2021 Master Push

**Platform:** Windows 10

**Steps to Reproduce:**

- 

1. Upload a file containing a tablature.
2. Make a change to tablature
3. Click "Convert" Button
4. **Save PopUp**: Save new changes to a txt file using "Save Changes" Button.

- 

- In the rare case, the change is not detected and the conversion occurs,  but going back and trying again leads into step 4.

5. Click "Convert" Button (Successful Conversion)

6. Click "Back"
7. Click "Convert" Button without making changes - changes made popup. However no new changes made and all changes have been saved

- Now every time the convert is attempted again - without changes - the save changes warning occurs

**Expected:**
If all changes have already been saved, the expectation is that step 7 above has no _Save Changes_ Popup, and just converts.

**Actual:**
Despite all changes being previously saved, the system incorrectly detects that a change has been made, and has a pop up indicating such.

**Priority:** Low - This bug is focused around User Experience, and seems to need specific steps to reproduce. For these reasons it may not be high priority as it is not a likely bug to encounter.

**Severity:** Medium - While this bug may not occur often, it is quite an annoyance on the user end when it does. Once the bug occurs, every convert attempt following has that incorrect _Save Changes_ Popup, With the popup needing to be acknowledged to continue, it may cause users to become fed up with the software.

**Screenshots:**

**File Uploaded**

![image](https://user-images.githubusercontent.com/36168874/112211158-f04eb000-8bf1-11eb-919a-b1605911075c.png)

**Changes Made and Convert Attempted**

![image](https://user-images.githubusercontent.com/36168874/112211964-d06bbc00-8bf2-11eb-85f0-c0be7b8f660c.png)

**Saved Changes to Save6.txt**

![image](https://user-images.githubusercontent.com/36168874/112212085-ee392100-8bf2-11eb-8e26-e4907fedefac.png)

**Successful First Conversion**

![image](https://user-images.githubusercontent.com/36168874/112212159-0610a500-8bf3-11eb-907c-07a91fddaa5b.png)

**No Changes Made, Conversion Attempted Again**
- **Results in incorrect popup, indicated a change was made and not saved**

![image](https://user-images.githubusercontent.com/36168874/112212308-30626280-8bf3-11eb-8c69-663db75d26b5.png)

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for pointing out this flaw. The bug has been resolved.
