### ISSUE TITLE
Bug: "Made Changes" Warning Appears Even Through No Changes Were Made 

### ISSUE THREAD

**Issue by Uthith18** [PBaciu/tabToMXL#29]
### Note:
It was only after writing this bug report, i've realized another classmate reported this same issue. Sorry in advance for the repetition. 

### Name:
 "Made Changes" Warning Appears Even Through No Changes Were Made 

### Description:

The pop-up warning, which encourages he user to save their tablature, due to changes being made appears even though no changes were made to the inputted tablature.  Below I posted two images, the first being a screenshot of the pasted tab being saved, and the second being the changes made warning, even though the no changes were made. 

**_Tab Being Saved_** 
<img width="907" alt="Screen Shot 2021-03-24 at 2 39 33 AM" src="https://user-images.githubusercontent.com/77372159/112336340-648d6000-8c93-11eb-9a04-788260197ce1.png">

Changes Made (Bug)
<img width="886" alt="Screen Shot 2021-03-24 at 2 38 27 AM" src="https://user-images.githubusercontent.com/77372159/112336572-90104a80-8c93-11eb-8316-d0833415a48e.png">

 
### Version:
Version 15.02 of Java SE Platform (as stated in User Manual)

### Platform:
MacOS Big Sur, Version 11.2.3

### Steps to Reproduce Bug:
1. Run the program and paste an input (which is supported by the program) into the "copy and paste window" (the input I used can be found in the "Input used" section)
2. Save the input, using the save button on the lower left side of the program 
3. Export tab into MusicXML 
4. Go back to look the tab you pasted 
5. Without making any changes, try to export again, and the "Warning: Changed Made" window will appear

### Expected Result:
The "Changes Made" pop-up should not appear, when no changes are made to a already saved tab 

### Actual Result:
The "Changes Made pop-up appears, when no changes are made to a already saved tab. A photo of the actual result is inserted below:

<img width="815" alt="Screen Shot 2021-03-24 at 11 33 11 AM" src="https://user-images.githubusercontent.com/77372159/112337890-b84c7900-8c94-11eb-8e87-01ad87041d71.png">

### Priority:
low

### Severity:
Medium ( Will affect work flow a little bit, but will not cause issues for a lot of customers)

### Status:
Ready for Development

### Input Used:

|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for pointing out this flaw. The bug has been resolved.
