### ISSUE TITLE
Bug: Unresponsive GUI

### ISSUE THREAD

**Issue by joshgenat** [PBaciu/tabToMXL#30]
## Name
Program GUI Not Responsive

## Description
With program GUI running, resizing the window has overlapped buttons and the title cutting off, not scaling to the size of the window properly.

## Steps to Reproduce
1. Run the program
2. Once GUI pops up, reduce the size gradually to see buttons overlapping

## Expected Result
Reducing window size will scale down appropriately, or have a set size/minimum limit. The GUI should not contain overlapped sections and maintain a clear user interface.

## Actual Result
Reducing window size keeps shrinking, however the scale of the buttons and sections do not shrink and eventually overlap each other. The text box eventually disappears as you keep shrinking as well. 

## Priority
Low

## Status 
Ready for Development

## Screenshot
![image](https://user-images.githubusercontent.com/77293319/112339526-1fb6f880-8c96-11eb-986c-04744fc1a0d0.png)

![image](https://user-images.githubusercontent.com/77293319/112339545-234a7f80-8c96-11eb-92e0-1988ee5c3038.png)

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for pointing out this issue. We have resolved this bug and will be updated in our next release.
