### ISSUE TITLE
Bug: XML Download not saved properly

### ISSUE THREAD

**Issue by joshgenat** [PBaciu/tabToMXL#33]
## Name
Program XML download does not save changes

## Description
With program running and inputting a tab to be converted, the output XML can save and download accordingly. 
However, when making a change to the output of the XML and downloading these new changes, the downloaded file does not seem to be recording these changes. For example, attempting to tweak the output XML and changing the fret will not appear if you were to click download again. I would have to go back to the beginning and modify the tab instead to see changes in the XML output.

## Steps to Reproduce
1. Run the program and input any working tab (the tab I used is provided below)
2. Convert and save first draft of the outputted XML. 
3. Make a change to that same XML output (my case I changed divisions) and click download again. Compare the two saved files and note that the modified XML does not record the changes.

## Expected Result
Making changes to XML output and downloading does alter the saved file

## Actual Result
Making changes to XML output and downloading does not alter the saved file

## Priority
High

## Status 
Ready for Development

## Screenshot
First Converted download (test5.musicxml) appears fine:
![image](https://user-images.githubusercontent.com/77293319/112347105-fc437c00-8c9c-11eb-92df-3042685c4ba5.png)

After making a change to "measure number: 2", saving as "test6.musicxml" and opening does not show any changes:

![image](https://user-images.githubusercontent.com/77293319/112347380-30b73800-8c9d-11eb-9c54-b35fef02470a.png)

**Comment by PBaciu** [comment]
I do not understand the relevancy of this bug. It does not make sense to change the first measure to be measure number 2. We handle this error by pre-determining the numbering of the measures. Please try adding a new measure before the measure for which you wish to change the number. If the issue persists, we will address it.

**Comment by joshgenat** [comment]
Yes, I am just taking note that any changes made does not translate to being saved on the newly downloaded file. 

Original Conversion:
![image](https://user-images.githubusercontent.com/77293319/112348703-71fc1780-8c9e-11eb-8cb3-9ccc51cd6437.png)

Changing pitch and octave, then saving on a new file, note that the step and octave aren't updated:

![image](https://user-images.githubusercontent.com/77293319/112348971-b4bdef80-8c9e-11eb-92c5-aca1cd33a379.png)

**Comment by PBaciu** [comment]
Thank you for the report, we will investigate.

**Comment by PBaciu** [comment]
Resolved
