### ISSUE TITLE
Time Signature Ignores User Input, Returns Default Value 4/4

### ISSUE THREAD

**Issue by Uthith18** [PBaciu/tabToMXL#34]
### Name:
Time Signature Ignores User Input, Returns Default Value 4/4

### Description:

When a value is entered into the "Time Signature" metadata, the inputted values are ignored and the program automatically sets a default value of 4/4. Below I provided a screenshot of the values inputted into the metadata and the resulting MusicXML code, with the 4/4 default values. 

**_Inputted Time Signature Values_** 
<img width="275" alt="Screen Shot 2021-03-24 at 12 38 33 PM" src="https://user-images.githubusercontent.com/77372159/112348222-00bc6480-8c9e-11eb-87c5-88fa6aeeb5a3.png">

**_MusicXML Code_** 
<img width="278" alt="Screen Shot 2021-03-24 at 12 38 15 PM" src="https://user-images.githubusercontent.com/77372159/112348335-1cc00600-8c9e-11eb-99bb-f3708d833b1e.png">

### Version:
Version 15.02 of Java SE Platform (as stated in User Manual)

### Platform:
MacOS Big Sur, Version 11.2.3

### Steps to Reproduce Bug:
1. Run the program, and paste a sample tab which is supported by the program. The tab I used can be found in the "User Input" section.
2. Enter a two values in an (X/Y) format into the "Time Signature" metadata and press convert
3. Look at lines 15-20 in the Music XML code,  where Beat and Beat-type are printed
4. The values will be 4 and 4, instead of what was put into the "Time Signature" metadata

### Expected Result:
The values in the MusicXML for beats and beat-type should changed based off what inputted in the "Time Signature" metadata. For example a input of 6/8 should produce the following:

<img width="253" alt="Screen Shot 2021-03-24 at 12 48 09 PM" src="https://user-images.githubusercontent.com/77372159/112349597-3f065380-8c9f-11eb-87d2-010d440fb7ad.png">

### Actual Result:
The values in the MusicXML for beats and beat-type are set to the default value of 4, regardless of what values are entered into the "Time Signature" metadata.

<img width="275" alt="Screen Shot 2021-03-24 at 12 19 49 PM" src="https://user-images.githubusercontent.com/77372159/112350204-ab815280-8c9f-11eb-9dc0-ba1a7995ee3e.png">

### Priority:
Low

### Severity:
High ( Will not affect work flow in the present, but important for the final submission for this course) 

### Status:
Ready for Development

### Input Used:
e|---------7-----7-|-8-----8-2-----2-|-0---------0-----|-----------------|
B|-------5---5-----|---5-------3-----|-------1-----1---|-0-1-1-----------|
G|-----5-------5---|-----5-------2---|-----2---------2-|-0-2-2-----------|
D|---7-----6-------|-5-------4-------|-3---------------|-----------------|
A|-t---------------|-----------------|-----------------|-2-0-0-------0-2-|
E|-----------------|-----------------|-----------------|-----------------|

**Comment by PBaciu** [comment]
We are aware of this issue, it has already been fixed in development and will be released in the next build.
