### ISSUE TITLE
Help Window Formatting

### ISSUE THREAD

**Issue by Nicolae-Semionov** [PBaciu/tabToMXL#40]
## Help Window Formatting

Raised by: Nicolae Semionov, 216468498

commit: f271a88

## Description
This issue was identified when exploring the programs different features. The help windows located on the main page and export window have some formatting issues

## Input & Result

As seen in the screenshots both help windows have some strange characters at the start of each paragraph.

Help 1
![help2](https://user-images.githubusercontent.com/46364601/112397879-4b0f0700-8cd9-11eb-8d74-4423a451a807.PNG)

Help 2
![help](https://user-images.githubusercontent.com/46364601/112397532-a987b580-8cd8-11eb-9f6b-f80bab392afd.PNG)

Priority: Low
This bug is minor and does not affect the function of the program. Should be a quick fix.

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for pointing out this flaw. We have resolved this issue now.
