### ISSUE TITLE
Program Accepts Incorrect Tempo Values

### ISSUE THREAD

**Issue by Nicolae-Semionov** [PBaciu/tabToMXL#42]
## Program Accepts Incorrect Tempo Values

Raised by: Nicolae Semionov, 216468498

commit: f271a88

## Description
This issue was identified when testing different values for time signature and tempo. The program correctly stops the user from entering the value 0 for time signature but does not do the same for tempo. This causes issues for some sites such as soundslice when converting back to tab.

## Input & Result
Input that caused the error (tempo = 0)
![tempo](https://user-images.githubusercontent.com/46364601/112399806-53694100-8cdd-11eb-89c5-c08fa3cbd3c5.PNG)

When trying to convert back using soundslice, site gets stuck processing
![Capture](https://user-images.githubusercontent.com/46364601/112399881-7b58a480-8cdd-11eb-8139-62794f739c78.PNG)

Priority: Med
This issue can be easily fixed by making the program force the user to enter a valid value just like in time signature. Without this fix the user might not know what's wrong with their input.

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for bringing this bug to light. We have fixed this issue and will be updated in our next release.
