### ISSUE TITLE
Suggestion: Save File Chooser Last Opened Directory

### ISSUE THREAD

**Issue by xzippyzachx** [PBaciu/tabToMXL#43]
**Version:** 823856f

**Platform:** Windows 10, Eclipse

**Reproduction:** 
1. Browse and select a text tablature
2. Browse again (It does not open to the last opened directory)

**Expected:** I find it would be very convenient if the file chooser opened to the last opened location. This would be more user friendly since you usually want to select files from the same directory multiple times.

**Actual:** The file chooser always opens to the default directory. This can be annoying if you want to select files from the same directory many times.

**Priority:** Low

**Severity:** Medium - This is not required but would be convenient

**Screenshots:**
![image](https://user-images.githubusercontent.com/33043402/112401168-4ef25780-8ce0-11eb-9954-2ae2f35d33ee.png)
_File chooser does not remember last opened directory_

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for your suggestion. We have implemented this feature and is now fully functional. Thank you.
