### ISSUE TITLE
Issues with window resizing

### ISSUE THREAD

**Issue by qurafa** [PBaciu/tabToMXL#46]
**Version:**  TabToMXL - March 17, 2021 Master Push

**Platform:** 
macOS Big Sur Version 11.0.1
Eclipse
Java Version 15

**Steps to reproduce:**
- Run the application in Eclipse
- Move your mouse to the edge of the pop up so you get the arrows that show that you can resize the window
- Resize the window.

**Expected:** the window would resize and rescale the window without any issues

**Actual:** the buttons and text were overlapping and crossing over each other

**Priority:** Low - because it needs to be fixed, but it can be put to the end after all the main features are executed

**Severity:** Low - because it doesn't affect the main functions of the project

**Screenshot:**
![image](https://user-images.githubusercontent.com/57468292/112405548-de9c0400-8ce8-11eb-8bd7-da0097340096.png)

**Screenshot:**
![image](https://user-images.githubusercontent.com/57468292/112405641-0be8b200-8ce9-11eb-8c2c-769cf450ee4a.png)

**Comment by Kumar-Venkatessh-216693764** [comment]
Thank you for Pointing out this flaw. We will fix this before the next release for our GUI.

**Comment by Kumar-Venkatessh-216693764** [comment]
Resolved.
