### ISSUE TITLE
Pulloff not working as expected 

### ISSUE THREAD

**Issue by Yalzahed** [PBaciu/tabToMXL#47]
Version: March 17 2021 Master

Platform: 
Windows 10
intellij IDEA
Java 15.0.2

Reproduction: 
Paste the following tab: 
e|-----------------|
B|-----7-----------|
G|---------------7-|
D|---------5-------|
A|-----------------|
E|-8p5-------------|

Time Signature: 4/4
Tempo:120

Expected: 
a pull-off between the first two frets which are an 8 and a 5 respectively 
etc: 
![ours pull off](https://user-images.githubusercontent.com/32556583/112405608-ff645980-8ce8-11eb-9dbb-a013be307ebd.jpg)

Actual:
no pull-off is shown and the first two notes are displayed as a 5 and a 5.  (On SoundSlice)
![pulloffTest patrick](https://user-images.githubusercontent.com/32556583/112405686-2589f980-8ce9-11eb-82b8-7d0751f834fd.jpg)

No pull-off is shown, the first two notes are 8 and 8  and the rest of the notes are not displayed (OpenSheetMusicDisplay)
![image](https://user-images.githubusercontent.com/32556583/112405940-a0ebab00-8ce9-11eb-9269-06a0001b69a7.png)

Priority level: High- if Pull-offs are in the tab, the rest of the notes are not displayed if the user is using OpenSheetMusicDisplay as their viewer

Severity level: High - Pull-offs are mentioned as a supported feature

**Comment by PBaciu** [comment]
Resolved
